### ISSUE TITLE
No puedo acceder a Miro

### ISSUE THREAD

**Issue by JorgeLacalle** [eeenajenaciones/estudio_territorios_digitales#4]
Lo comenté el lunes en clase porque no pude subir la entrega de ese día pero sigo teniendo el mismo problema. Al acceder al Miro del curso no me deja editar ni crear nada, solo pone que estoy en ese tablero de visitante y que tengo acceso de solo lectura.
 Me ha dicho Pepe que lo escriba por aqui, pongo mis correos por si ayuda:

j.lacalle@alumnos.upm.es
j.lacalle98@gmail.com

Gracias de antemano

**Comment by eivillamuelas** [comment]
Hola Jorge, escribiste tu correo en el excel?

**Comment by JorgeLacalle** [comment]
Lo escribí en el papel que pasaron el primer dia de clase, no se si a eso te refieres con el excel

**Comment by rdelsog** [comment]
vamos a ver jorge... un excel NO ES UN PAPEL!!!!

Hemos pasado como 5 veces la tabla de excel PARA QUE CADA ESTUDIANTE PONGA ALLI SU EMAIL! y lo hemos contado en clase dos. 

Busca el link de whatsapp a la tabla de excel y ponlo ahí

**Comment by JorgeLacalle** [comment]
Hasta ayer no estaba en el grupo de WhatsApp, no lo había recibido. Yo puse desde el primer momento mi numero de teléfono y mi email en ese papel inicial, pero al parecer no se me metió en ese grupo. No podía saber que existía ese excel. Y si se comentó en clase pero no tenia la información de que existía no relacioné.
Gracias, ahora lo solicito por el WhatsApp.

**Comment by JorgeLacalle** [comment]
Ya he puesto el email en el Excel, cierro este problema del foro
