### ISSUE TITLE
Problemas con el codigo 🌐 Generación de modelos 3D (DreamGaussian)

### ISSUE THREAD

**Issue by LuciaDRey** [eeenajenaciones/estudio_territorios_digitales#6]
He intentado generar la malla con diferentes imágenes, todas bien de tamaño (hasta con la propia imagen del ejemplo) y no para de señalarme error aqui.
![Captura de pantalla 2024-02-13 102016](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/ca61f338-b92c-4166-a363-78b7a5e0cd42)

**Comment by eeenajenaciones** [comment]
Hola Lucía y qué te aparece debajo, donde sale el resultado?

**Comment by LuciaDRey** [comment]
este mensaje
![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/a298c744-59c6-4997-82c9-5736fcc955f1)

**Comment by eeenajenaciones** [comment]
Y en la opción de cargar imagen que has puesto? Te sale la imagen? Has probado cambiando quitando espacio a los nombres de las carpetas y archivos? Debería funcionar da igual los nombres pero por si acaso

He cambiado cosas en el cuaderno. Sal y vuelve a entrar a ver si te deja

**Comment by LuciaDRey** [comment]
muchisimas gracias, habia comprobado todo y ahora ese paso si me va. Solo me da error al generar la malla
![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/9b929bbf-c09e-4edd-ab15-08b1a2191540)
![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/d2bb5c3a-da86-47ca-b45c-25f1f6d95eae)
![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/4b1712af-2c1b-44db-a05c-b50cedd5b6bd)

**Comment by eeenajenaciones** [comment]
Bien poco a poco. 

Parece que no te ha cargado bien la primera celda por que te falta una librería. Si abres la primera celda te sale algún error o algo en rojo?

Gracias y perdona por los erroresss

**Comment by LuciaDRey** [comment]
no entiendo a que te refieres con celda, a este enlace?
![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/62c7ad9d-594a-474c-b11d-b452ba5d267d)

**Comment by eeenajenaciones** [comment]
Hola perdona, celda me refiero a la caja que le das play. 
Si subes a la primera que pone instalar librerías te debería salir el error que te comento

**Comment by eeenajenaciones** [comment]
El primer error que te sale es ModuleNotFoundError: No module named 'diff_gaussian_rasterization' es significa que ese modulo o librería por alguna razón no se te ha cargado

**Comment by LuciaDRey** [comment]
Hola, lo único rojo que me aparece es esto, aunque no creo que sea un error. La carpeta que dice en el error que he mandado que no encuentra si que esta supuestamente instalada.

![image](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/159890491/15bb21e1-8eb3-4587-8594-4afdb3bd7720)

**Comment by eeenajenaciones** [comment]
Cierto. puedes probar a cerrar y abrir el cuaderno de nuevo? que puse una cosa para que se borrase el error y no se ve

**Comment by eeenajenaciones** [comment]
para cerrar la sesión completamente pulsa ahí y así se reesetea desde zero
![desconectar](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/157328061/4396dd6c-ed5f-406a-bdac-24228f131415)

**Comment by LuciaDRey** [comment]
Holaa, habia tenido que parar porque habia llegado al limite. Ahora me vuelve a dar el error del principio

**Comment by eeenajenaciones** [comment]
Pues si quieres lo vemos esta tarde en clase

**Comment by eeenajenaciones** [comment]
Cierro el hilo, si no funcionó lo abrimos de nuevo <3
