### ISSUE TITLE
ERROR en generar malla collab.

### ISSUE THREAD

**Issue by DiegoSobrinoCorral** [eeenajenaciones/estudio_territorios_digitales#7]
![WhatsApp Image 2024-02-14 at 09 58 44 (1)](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/160007364/ff44da76-a012-4cc8-bc1b-0a7ca2ba0c06)
![WhatsApp Image 2024-02-14 at 09 58 44](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/160007364/bdb21348-ec95-41eb-8b79-8a8f47671345)
![WhatsApp Image 2024-02-14 at 09 58 45](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/160007364/4d5c9f73-a3fd-45dd-a68a-e0b602e591d0)

He leido el comentario de Lucia de rey y le daba el mismo error al final. No se que solucion tuvo al final. ¿si esto no funciona como podemos hacer esta entrega? ¿hay alguna otra herramienta?

**Comment by eeenajenaciones** [comment]
Hola Diego, esta tarde lo vemos en clase. Ocurre en el mismo sitio pero no es el mismo error. En su caso no le estaba cargando una librería en tu caso sin más información del resto no te sé decir.

Me puedes compartir la imagen que has usado y pruebo yo? Gracias

**Comment by DiegoSobrinoCorral** [comment]
![ilu 1](https://github.com/eeenajenaciones/estudio_territorios_digitales/assets/160007364/66ba7736-07bb-4a5e-9998-a9a1c6a41d1c)

He usado esta para probar. El resto me funcionaba bien y todo había cargado. Solo falla el último.
Muchas gracias!

**Comment by eeenajenaciones** [comment]
Cierro el hilo, si no funcionó lo abrimos de nuevo <3
